### ISSUE TITLE
How can I access my server with https

### ISSUE THREAD

**Issue by minilynn** [j6mes/httplib#30]
I'm connecting to my server with https, but fail to build connection with SSL/TLS
My server working with private certificate generated by openssl

**Comment by j6mes** [comment]
.Net will reject invalid certificates by default (this is expected behaviour). Allowing invalid certificates in production will create security risks (such as allowing potential MITM attacks), but is possible:

`ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };`

See this for more detail: https://stackoverflow.com/questions/526711/using-a-self-signed-certificate-with-nets-httpwebrequest-response
